name: iOS starter workflow

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Build Project
    runs-on: macOS-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      
    - name: Set Gems
      run: |
        gem install bundler
        bundle install
      
    - name: Set Xcode version
      uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: 14.0.1
        
    - name: Build
      run: |
        set -o pipefail
        xcodebuild build \
        -scheme Project-Bird \
        -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' \
        | xcpretty
        
  test:
    name: Test Project
    needs: build
    runs-on: macOS-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Set Gems
      run: |
        gem install bundler
        bundle install
        
    - name: Set Xcode version
      uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: 14.0.1

    - name: Test
      run: |
        set -o pipefail
        xcodebuild test \
        -scheme Project-Bird \
        -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' \
        | xcpretty
